gruene_cms/forms.py
import datetime

from django import forms
from gruene_cms.models import TaskItem, CalendarItem
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from django.apps import apps


class TaskCreateForm(forms.ModelForm):
    assigned_to_users = forms.ModelMultipleChoiceField(
        queryset=User.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True,
        label=_("Assign Task to")
    )

    class Meta:
        model = TaskItem
        fields = ["category", "summary", "assigned_to_users"]


class TaskUpdateForm(forms.ModelForm):
    assigned_to_users = forms.ModelMultipleChoiceField(
        queryset=User.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True,
        label=_("Assign Task to")
    )
    progress = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={'type': 'range', 'step': '10'}
        ),
        label=_('Progress')
    )
    priority = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={'type': 'range', 'step': '1', 'max': 2}
        ),
        label=_('Task Priority')
    )

    class Meta:
        model = TaskItem
        fields = ["category", "summary", "assigned_to_users", "progress", "priority"]


class SearchForm(forms.Form):
    q = forms.CharField(max_length=100, help_text=_('max 100 chars'))

    def __init__(self, *args, **kwargs):
        super(SearchForm, self).__init__(*args, **kwargs)
        self.fields['q'].widget.attrs.update({'class': 'form-control form-control-lg'})


class WebDAVUploadForm(forms.Form):
    upload_file = forms.FileField(label=_('File'))
    location_dir = forms.ChoiceField(choices=[
        ['/', _('/ (root folder)')]
    ], label=_('storage location'))
    location_dir_new = forms.CharField(
        max_length=50,
        required=False,
        help_text=_('Name of a new sub storage location. Keep empty to save the file in the selected storage location.'),
        label=_('New sub storage location')

    )
    backup_existing_file = forms.BooleanField(
        initial=False,
        required=False,
        label=_('Backup'),
        help_text=_('Backups existing file if the same file exists')
    )

    def __init__(self, *args, **kwargs):
        possible_locations_dirs = kwargs.pop('possible_locations_dirs', None)
        #print("possible_locations_dirs", possible_locations_dirs)
        super(WebDAVUploadForm, self).__init__(*args, **kwargs)
        #print("self.fields['location_dir'].choices", self.fields['location_dir'].choices)
        if isinstance(possible_locations_dirs, list):
            self.fields['location_dir'].choices += possible_locations_dirs


class CreateCalendarItemModelForm(forms.ModelForm):
    date = forms.DateField(label=_("Date"), help_text=_('Format: day.month.year'))
    time = forms.TimeField(label=_('Time'), help_text=_('Format: hour:minute'))
    duration = forms.TimeField(required=False, widget=forms.TimeInput, label=_('Duration'), help_text=_('Format: hour:minute'))

    class Meta:
        model = CalendarItem
        fields = [
            'date',
            'time',
            'calendar',
            'title',
            'subtitle',
            'location',
            'duration',
            #'date',
            #'hour',
            #'duration',
        ]


class NewstickerFilterForm(forms.Form):
    date = forms.DateField(
        required=False,
        widget=forms.DateInput(attrs={'type': 'date'}),
        label='Datum'
    )
    days = forms.IntegerField(
        label='Zusätzliche Tage',
        required=False,
        initial=0,
        max_value=10
    )
    collapse_cat = forms.ModelChoiceField(
        label='Kategorie',
        queryset=apps.get_model('newsticker.TickerCategory').objects.all(),
        required=False
    )
    show_all = forms.BooleanField(
        label='Alle Ausklappen',
        required=False,
        initial=True
    )

gruene_cms/views/search.py
from django.urls import reverse
from django.views import generic
from django.db.models import Q
from django.apps import apps
from gruene_cms.forms import SearchForm
from gruene_cms.views.base import AppHookConfigMixin
from gruene_cms.models import NewsItem, CalendarItem


class SearchView(AppHookConfigMixin, generic.FormView):
    form_class = SearchForm
    template_name = 'gruene_cms/apps/search.html'

    def form_valid(self, form):
        return self.form_invalid(form=form)

    def get_context_data(self, **kwargs):
        ctx = super(SearchView, self).get_context_data(**kwargs)

        form = ctx['form']
        if form.is_valid():
            q = form.cleaned_data.get('q')

            news_qs = NewsItem.objects.filter(
                Q(title__icontains=q) |
                Q(subtitle__icontains=q) |
                Q(keywords__iexact=q) |
                Q(summary__icontains=q) |
                Q(content__icontains=q),
                categories__is_public=True
            )

            news_qs = news_qs.order_by('-published_from').distinct()[:10]

            for news in news_qs:
                if news.newsfeedreader_external_link:
                    news.detail_link = news.newsfeedreader_external_link
                else:
                    news.detail_link = reverse('gruene_cms_news:detail', kwargs={'slug': news.slug})

                # monkeypatch for template:
                news.item_col_lg_config = '12'
                news.item_col_xl_config = '6'

            cal_qs = CalendarItem.objects.filter(
                Q(title__icontains=q) |
                Q(location__icontains=q)
            ).distinct()[:10]

            # monkeypatch for template
            for cal in cal_qs:
                cal.linked_url_external = False
                if cal.linked_page:
                    cal.linked_url = cal.linked_page.get_absolute_url()
                if cal.linked_news:
                    cal.linked_url = reverse('gruene_cms_news:detail', kwargs={'slug': cal.linked_news.slug})
                if cal.external_link:
                    cal.linked_url = cal.external_link
                    cal.linked_url_external = True

            # Newsticker
            newsticker_qs = apps.get_model('newsticker.TickerItem').objects.none()
            if (len(q) > 5) or (q in ['CDU', 'CSU', 'AfD', 'Linke', 'Grüne', 'SPD', 'FDP']):
                newsticker_qs = apps.get_model('newsticker.TickerItem').objects.filter(
                    Q(headline__icontains=q) |
                    Q(summary__icontains=q)
                ).order_by('-pub_dt').distinct()[:10]


            ctx.update({
                'news_qs': news_qs,
                'cal_qs': cal_qs,
                'newsticker_qs': newsticker_qs,
                'has_results': any([
                    news_qs.exists(),
                    cal_qs.exists(),
                    newsticker_qs.exists()
                ]),
                # monkeypatch for template:
                'news_instance': {
                    'title_h': 3,
                    'title_subtitle_h': 4,
                    'enable_masonry': False,
                    'show_feed_title': True,
                    'show_date': True
                }
            })

        news_keywords_qs = NewsItem.objects.filter(
            categories__is_public=True
        ).values_list('keywords', flat=True)

        news_keywords = []
        for nkw in news_keywords_qs:
            for kw in nkw.split(','):
                if kw not in news_keywords:
                    news_keywords.append(kw)

        ctx.update({
            'news_keywords': news_keywords,
            'is_post': self.request.method.lower() == 'post'
        })

        return ctx


    #def get_form_kwargs(self):
    #    q = self.request.GET.get('q')
    #    initials = super(SearchView, self).get_form_kwargs()
    #    initials[q] = q
    #    return initials

gruene_cms/templates/gruene_cms/apps/login.html
{% extends "gruene_v1.html" %}
{% load cms_tags menu_tags sekizai_tags static i18n django_bootstrap5 %}
{% block page_subtitle %}
  <a class="text-white" href="/">{% page_attribute "title" request.current_page.get_root %}</a>
  {% show_breadcrumb 1 "gruene_cms/breadcrumb.html" %}

  <!-- {% page_attribute "page_title" %} -->
{% endblock %}

{% block content %}
  <div class="container mt-5">
    <div class="row">
      <div class="col col-12 col-md-6 col-lg-4">
        <h2 class="mb-3">Anmelden</h2>
        <p class="mb-4"><span class="badge bg-danger">{{ error_msg }}</span></p>
        <form action="{% url 'gruene_cms_dashboard:db_login' %}?next={{ next }}" enctype="multipart/form-data" method="post">
          {% csrf_token %}
          {% bootstrap_form form layout='floating' %}

          {% bootstrap_button button_type="submit" content="Anmelden" %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}

gruene_cms/templates/gruene_cms/apps/search.html
{% extends "gruene_v1.html" %}
{% load cms_tags menu_tags sekizai_tags static i18n %}
{% block page_subtitle %}
  <a class="text-white" href="/">{% page_attribute "title" request.current_page.get_root %}</a>
  {% show_breadcrumb 1 "gruene_cms/breadcrumb.html" %}

  <!-- {% page_attribute "page_title" %} -->
{% endblock %}

{% block content %}

  <div class="container pt-5">
    <div class="row">
      <div class="col col-12">
        <h2 class="pb-5">{% trans "Search" %}</h2>
        <form action="" method="post" id="search">
          {% csrf_token %}
          <div class="row g-3 align-items-baseline">
            <div class="col-auto">
              <label for="id_q" class="col-form-label">{% trans "Search for" %}</label>
            </div>
            <div class="col-8">
              {{ form.q }}
              <span id="id_q_helptext" class="form-text">
                {{ form.q.help_text }}
              </span>
            </div>
            <div class="col-auto">
              <button type="submit" class="btn btn-primary">{% trans "Search" %}</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>

  {% if has_results %}
    <div class="container pt-5">
      <div class="row">
        <div class="col col-12">
          <h2 class="pb-5">{% trans "Results" %}</h2>
          {% if cal_qs.exists %}
            <div class="pb-5">
              <h3 class="">{% trans "Calendar" %}</h3>
              {% include 'gruene_cms/plugins/calendar_node_table_2.html' with calendar_items=cal_qs %}
            </div>
          {% endif %}

          {% if news_qs.exists %}
            <h3 class="">{% trans "News" %}</h3>
            {% include 'gruene_cms/plugins/news_card_v2_node.html' with news_items=news_qs instance=news_instance %}
          {% endif %}

          {% if newsticker_qs.exists %}
            <h3 class="">Newsticker</h3>
            <div class="container-full news-item mb-5">
              <div class="row g-5">
              {% for ni in newsticker_qs %}
                <div class="col col-12 col-lg-6">

                  <div class="card shadow-lg">
                    <div class="card-body">
                      <a href="{{ ni.get_absolute_url }}" class="">
                        <h3 class="news-title">{{ ni.headline }}</h3>
                      </a>
                      <div class="news-summary">
                        {{ ni.get_rendered_summary|truncatewords_html:15|safe }}
                      </div>
                    </div>
                    <div class="card-footer">
                      <div class="container-fluid px-0">
                        <div class="row">
                          <div class="col-6">
                            <a href="{{ ni.get_absolute_url }}" class="continue-reading pt-0">
                              Weiter­lesen
                            </a>
                          </div>
                          <div class="col-6 align-content-center">
                            <span class="text-muted small float-end">
                              <i>{{ ni.category }}</i>
                              <span class="meta-seperator"> </span>
                              <strong>{{ ni.pub_dt|date:"SHORT_DATE_FORMAT" }}</strong>
                            </span>
                          </div>
                        </div>
                      </div>
                    </div>

                  </div>


                </div>
              {% endfor %}
              </div>
            </div>
          {% endif %}

        </div>
      </div>
    </div>
  {% else %}
    {% if is_post %}
      <div class="container pt-5">
        <div class="row">
          <div class="col col-12">
            <div class="alert alert-secondary" role="alert">
              {% trans "No matches found." %}
            </div>
          </div>
        </div>
      </div>
    {% endif %}
  {% endif %}

  <div class="container pt-5 pb-5">
    <div class="row">
      <div class="col col-12">
        <div class="card shadow-sm">
          <div class="card-header">
            <h2 class="card-title small mb-0">
              {% trans "Keywords" %}
            </h2>
          </div>
          <div class="card-body">
            <div class="keywords mt-3">
              <ul>
                {% for kw in news_keywords %}
                  <li  class="m-1">
                    <a class="keyword post-to-search" href="#" rel="tag" data-search="{{ kw }}">{{ kw }}</a>
                  </li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <script>
      $(document).ready(function() {
          $('.post-to-search').click(function(e) {
              e.preventDefault();
              $('#search input[name="q"]').val($(this).attr('data-search'));
              $('#search').submit();
          });
      });
    </script>

{% endblock %}